# Finance Chain Configuration
chain:
  name: "bloqz-finance"
  chain_id: "bloqz-finance-1"
  version: 1
  min_gas_price: "0.001ufin"

# Genesis Configuration
genesis:
  genesis_time: "2024-01-01T00:00:00Z"
  chain_id: "bloqz-finance-1"
  initial_height: "1"
  
  # Consensus Parameters
  consensus_params:
    block:
      max_bytes: "22020096"
      max_gas: "-1"
      time_iota_ms: "1000"
    evidence:
      max_age_num_blocks: "100000"
      max_age_duration: "172800000000000"
      max_bytes: "1048576"
    validator:
      pub_key_types: ["ed25519"]
    version: {}

# Validator Configuration
validators:
  min_self_delegation: "1"
  min_commission_rate: "0.05"
  max_commission_rate: "0.20"
  max_commission_change_rate: "0.01"
  blocks_per_year: "6311520"

# Token Configuration
token:
  base_denom: "ufin"
  display_denom: "FIN"
  decimals: 6
  initial_supply: "1000000000000"

# Industry-Specific Profile Verification
profile_verification:
  enabled: true
  industry_requirements:
    - name: "financial_institution"
      documents:
        - "banking_license"
        - "regulatory_compliance"
        - "aml_certification"
    - name: "investment_firm"
      documents:
        - "sec_registration"
        - "investment_advisor_license"
    - name: "insurance_provider"
      documents:
        - "insurance_license"
        - "capital_adequacy_proof"
  verification_period: "8760h"  # 1 year
  renewal_reminder: "720h"    # 30 days before expiry

# Document Hash Storage
document_storage:
  enabled: true
  industry_specific_types:
    - name: "financial_statements"
      retention: "87600h"  # 10 years
      required_signatures: 2
    - name: "audit_reports"
      retention: "43800h"  # 5 years
      required_signatures: 1
    - name: "regulatory_filings"
      retention: "87600h"  # 10 years
      required_signatures: 2
  encryption_required: true
  audit_trail: true

# Integration Service Verification
integration_verification:
  enabled: true
  financial_services:
    - name: "payment_processing"
      requirements:
        - "pci_dss_compliance"
        - "api_security_audit"
    - name: "trading_systems"
      requirements:
        - "exchange_api_verification"
        - "latency_requirements"
    - name: "banking_core"
      requirements:
        - "core_banking_certification"
        - "security_compliance"

# IBC Configuration
ibc:
  enabled: true
  transfer_enabled: true
  transfer_port: "transfer"
  commitment_prefix: "bloqz/finance"
  max_expected_time_per_block: "30000000000" # 30s in nanoseconds

  # IBC Client Configuration
  client:
    trusted_height: "1-1"
    trusting_period: "336h"
    unbonding_period: "504h"
    max_clock_drift: "10s"
    allow_update_after_expiry: true
    allow_update_after_misbehaviour: true

# Hub Connection Settings
hub_connection:
  enabled: true
  chain_id: "bloqz-hub-1"
  client_id: "07-tendermint-0"
  connection_id: "connection-0"
  channel_id: "channel-0"
  port_id: "transfer"
  version: "ics20-1"
  verification_sync: true
  document_sync: true

# Industry-Specific Settings
finance:
  modules:
    - defi
    - lending
    - trading
    - payments
  features:
    defi:
      enabled: true
      max_leverage: 3
      min_collateral: "1000"
    lending:
      enabled: true
      max_loan_duration: "8760h" # 1 year
      min_collateralization: "150"
    trading:
      enabled: true
      max_order_size: "1000000"
    payments:
      enabled: true
      max_transaction_size: "1000000"

# State Sync Configuration
state_sync:
  enabled: true
  rpc_servers: []
  trust_height: 0
  trust_hash: ""
  trust_period: "168h"

# P2P Configuration
p2p:
  laddr: "tcp://0.0.0.0:26656"
  external_address: ""
  seeds: []
  persistent_peers: []
  max_num_inbound_peers: 40
  max_num_outbound_peers: 10
  allow_duplicate_ip: false

# API Configuration
api:
  enable: true
  address: "tcp://0.0.0.0:1317"
  max_open_connections: 1000
  rpc_read_timeout: 10
  rpc_write_timeout: 10
  max_body_bytes: 1000000

# Security Settings
security:
  min_validator_stake: "100000ufin"
  slash_fraction_double_sign: "0.05"
  slash_fraction_downtime: "0.01"
  security_contact: "security@bloqz.io"
  
# Recovery Configuration
recovery:
  enabled: true
  max_attempts: 5
  backup_interval: "24h"
  retention_period: "72h"
